version: '3'
services:
  mysql:
    image: mysql:latest
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - app-network

  nodejs:
    image: node:14
    working_dir: /app
    volumes:
      - ./app:/app
    env_file: ./.env
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_DIALECT: ${DB_DIALECT}
      DB_PORT: ${DB_PORT}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:1212"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
